webtalk_init -webtalk_dir /ad/eng/users/r/y/ryanbs/Desktop/EC413_Lab4/EC413_Lab4.sim/sim_1/behav/xsim/xsim.dir/FA_64bit_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 21 17:11:24 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211078688_174135686_206649660_625" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "952d8444-a3db-4f0d-b05f-aaa8e38b5680" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0038239ec438456dac18c3d7854a015d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.7.1908 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2963.366 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126920_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1935805062 -regid "211078688_174135686_206649660_625" -xml /ad/eng/users/r/y/ryanbs/Desktop/EC413_Lab4/EC413_Lab4.sim/sim_1/behav/xsim/xsim.dir/FA_64bit_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /ad/eng/users/r/y/ryanbs/Desktop/EC413_Lab4/EC413_Lab4.sim/sim_1/behav/xsim/xsim.dir/FA_64bit_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /ad/eng/users/r/y/ryanbs/Desktop/EC413_Lab4/EC413_Lab4.sim/sim_1/behav/xsim/xsim.dir/FA_64bit_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
