#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Feb 28 15:01:01 EST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_ALU_behav -key {Behavioral:sim_1:Functional:tb_ALU} -tclbatch tb_ALU.tcl -log simulate.log"
xsim tb_ALU_behav -key {Behavioral:sim_1:Functional:tb_ALU} -tclbatch tb_ALU.tcl -log simulate.log

